"""create profit_snapshots

Revision ID: 04515366b555
Revises: ecb524581e71
Create Date: 2026-08-03 06:37:02.876596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04515366b555'
down_revision: Union[str, None] = 'ecb524581e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('scenario', sa.Enum('pessimistic', 'standard', 'optimistic', name='profit_scenario'), nullable=False),
    sa.Column('displayed_profit', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('excluded_cost_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_unconfirmed_cost', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['release_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_snapshots_calculated_at'), 'profit_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_profit_snapshots_event_id'), 'profit_snapshots', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_snapshots_event_id'), table_name='profit_snapshots')
    op.drop_index(op.f('ix_profit_snapshots_calculated_at'), table_name='profit_snapshots')
    op.drop_table('profit_snapshots')
    # ### end Alembic commands ###

    # autogenerateはPostgreSQLのCREATE TYPE(Enum)をDROP TYPEで戻さないため明示的に削除する
    # (task2のマイグレーションと同じ理由。alembic/versions/ecb524581e71_*.py参照)
    op.execute("DROP TYPE IF EXISTS profit_scenario")
