"""create manual_review_tasks

Revision ID: 21459e2abda7
Revises: ac68151d8952
Create Date: 2026-08-05 09:48:33.946733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21459e2abda7'
down_revision: Union[str, None] = 'ac68151d8952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_review_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_product_id', sa.UUID(), nullable=False),
    sa.Column('matched_product_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='manual_review_task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_review_tasks_candidate_product_id'), 'manual_review_tasks', ['candidate_product_id'], unique=False)
    op.create_index(op.f('ix_manual_review_tasks_matched_product_id'), 'manual_review_tasks', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_manual_review_tasks_status'), 'manual_review_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_review_tasks_status'), table_name='manual_review_tasks')
    op.drop_index(op.f('ix_manual_review_tasks_matched_product_id'), table_name='manual_review_tasks')
    op.drop_index(op.f('ix_manual_review_tasks_candidate_product_id'), table_name='manual_review_tasks')
    op.drop_table('manual_review_tasks')
    # ### end Alembic commands ###
