"""create opportunities

Revision ID: 5084f5591138
Revises: 04515366b555
Create Date: 2026-08-03 09:13:14.866309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5084f5591138'
down_revision: Union[str, None] = '04515366b555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('best_channel_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('match_status', sa.Enum('auto_match', 'high_probability_match', 'needs_review', 'different_product', 'manually_confirmed', name='opportunity_match_status'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['release_events.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'best_channel_name', name='uq_opportunities_event_channel')
    )
    op.create_index(op.f('ix_opportunities_event_id'), 'opportunities', ['event_id'], unique=False)
    op.create_index(op.f('ix_opportunities_product_id'), 'opportunities', ['product_id'], unique=False)
    op.create_index(op.f('ix_opportunities_score'), 'opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_product_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_event_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###

    # autogenerateはPostgreSQLのCREATE TYPE(Enum)をDROP TYPEで戻さないため明示的に削除する
    op.execute("DROP TYPE IF EXISTS opportunity_match_status")
