"""create pending_notifications

Revision ID: 7b788e3dd59e
Revises: 21459e2abda7
Create Date: 2026-08-06 15:53:50.275869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b788e3dd59e'
down_revision: Union[str, None] = '21459e2abda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('release_event_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('embed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_review_task_id', sa.String(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='pending_notification_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discord_message_id', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['release_event_id'], ['release_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_notifications_opportunity_id'), 'pending_notifications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_pending_notifications_release_event_id'), 'pending_notifications', ['release_event_id'], unique=False)
    op.create_index(op.f('ix_pending_notifications_status'), 'pending_notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_notifications_status'), table_name='pending_notifications')
    op.drop_index(op.f('ix_pending_notifications_release_event_id'), table_name='pending_notifications')
    op.drop_index(op.f('ix_pending_notifications_opportunity_id'), table_name='pending_notifications')
    op.drop_table('pending_notifications')
    # ### end Alembic commands ###
