"""create products categories brands regions shops sources release_events

Revision ID: ecb524581e71
Revises: b44272b2f305
Create Date: 2026-08-03 04:43:53.374740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb524581e71'
down_revision: Union[str, None] = 'b44272b2f305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prefecture', sa.String(), nullable=False),
    sa.Column('area_group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_area_group'), 'regions', ['area_group'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('collector_key', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collector_key')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_name_trgm', 'products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('online', 'store', name='shop_type'), nullable=False),
    sa.Column('granularity', sa.Enum('single_store', 'regional_chain', 'national_chain', name='shop_granularity'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('jan', 'isbn', 'sku', 'model', name='product_identifier_type'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'type', 'value', name='uq_product_identifiers_product_type_value')
    )
    op.create_index(op.f('ix_product_identifiers_value'), 'product_identifiers', ['value'], unique=False)
    op.create_table('release_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('normal_sale', 'reservation', 'lottery', 'restock', 'store_arrival', name='release_event_type'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('announce_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_limit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fulfillment_type', sa.Enum('store_pickup', 'online_shipping', 'both', name='fulfillment_type'), server_default='online_shipping', nullable=False),
    sa.Column('region_override', sa.String(), nullable=True),
    sa.Column('region_display_text', sa.String(), nullable=True),
    sa.Column('region_source', sa.Enum('exact', 'prefecture', 'area_group', 'unknown', name='region_source'), server_default='unknown', nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_source', sa.Enum('confirmed', 'unknown', name='deadline_source'), server_default='unknown', nullable=False),
    sa.Column('store_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('online_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shop_id', 'event_type', 'start_at', name='uq_release_events_product_shop_type_start')
    )
    op.create_index(op.f('ix_release_events_deadline_at'), 'release_events', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_release_events_status'), 'release_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_events_status'), table_name='release_events')
    op.drop_index(op.f('ix_release_events_deadline_at'), table_name='release_events')
    op.drop_table('release_events')
    op.drop_index(op.f('ix_product_identifiers_value'), table_name='product_identifiers')
    op.drop_table('product_identifiers')
    op.drop_table('shops')
    op.drop_index('ix_products_name_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('sources')
    op.drop_index(op.f('ix_regions_area_group'), table_name='regions')
    op.drop_table('regions')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###

    # autogenerateはPostgreSQLのCREATE TYPE(Enum)をDROP TYPEで戻さないため明示的に削除する
    for enum_name in (
        "release_event_type",
        "deadline_source",
        "region_source",
        "fulfillment_type",
        "product_identifier_type",
        "shop_granularity",
        "shop_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
