"""add product_url and apply_url to release_events

Revision ID: ed8ed7ce37ca
Revises: 5084f5591138
Create Date: 2026-08-03 09:16:05.746981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8ed7ce37ca'
down_revision: Union[str, None] = '5084f5591138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_events', sa.Column('product_url', sa.String(), nullable=False))
    op.add_column('release_events', sa.Column('apply_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_events', 'apply_url')
    op.drop_column('release_events', 'product_url')
    # ### end Alembic commands ###
